<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OpenScreenRecorder.Core\OpenScreenRecorder.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.2.0" />
    <PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.26100.7175" />
    <PackageReference Include="ScreenRecorderLib" Version="6.6.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Platform Condition="'$(Platform)' == ''">x64</Platform>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Platform)' == 'AnyCPU'">
    <Platform>x64</Platform>
  </PropertyGroup>

</Project>
